// <auto-generated />
using MVC_CodeFirst_StoicWorkout.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_CodeFirst_StoicWorkout.Migrations
{
    [DbContext(typeof(StoicWorkoutContext))]
    [Migration("20250902114048_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_CodeFirst_StoicWorkout.Models.Entities.Exercise", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Dip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lunge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MuscleUp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PullUp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PushUp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Squat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("MVC_CodeFirst_StoicWorkout.Models.Entities.Routine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DipSimple")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegsSimple")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MuscleUpSimple")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PullUpSimple")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PushUpSimple")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Routines");
                });
#pragma warning restore 612, 618
        }
    }
}
